# Generated by Django 4.0.10 on 2023-02-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('stats', models.JSONField()),
                ('types', models.JSONField(default=list)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('images', models.JSONField()),
                ('has_gender_differences', models.BooleanField()),
                ('local_area_encounters', models.CharField(max_length=20)),
                ('moves', models.JSONField()),
            ],
        ),
    ]
