# Generated by Django 4.0.10 on 2023-02-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='local_area_encounters',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(default={'attack': 0, 'defense': 0, 'happiness': 0, 'hp': 0, 'sp_attack': 0, 'sp_defense': 0, 'speed': 0}),
        ),
    ]
