# Generated by Django 4.0.10 on 2023-02-24 05:26

from django.db import migrations, models
import pokefinder.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0002_alter_pokemon_local_area_encounters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(default=pokefinder.models.default_stats),
        ),
    ]
