# Generated by Django 4.0.10 on 2023-02-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0003_alter_pokemon_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='local_area_encounters',
            new_name='location_area_encounters',
        ),
    ]
