# Generated by Django 4.0.10 on 2023-02-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0004_rename_local_area_encounters_pokemon_location_area_encounters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='location_area_encounters',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
