# Generated by Django 4.0 on 2023-02-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0005_alter_pokemon_location_area_encounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='polyline',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
