# Generated by Django 4.0 on 2023-02-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0006_pokemon_polyline_alter_pokemon_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='long',
            new_name='lng',
        ),
    ]
