version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend:
    build: 
      context: ./backend/server
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    # volumes:
    #   - ./backend:/app/backend
    depends_on:
      - db

volumes:
  db-data: