# Generated by Django 4.0.10 on 2023-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokefinder', '0005_alter_pokemon_location_area_encounters'),
        ('users', '0003_alter_user_password'),
        ('favorites', '0002_rename_favorites_userpokemonfavorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpokemonfavorites',
            old_name='pokemon',
            new_name='pokemon_id',
        ),
        migrations.RenameField(
            model_name='userpokemonfavorites',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userpokemonfavorites',
            unique_together={('user_id', 'pokemon_id')},
        ),
    ]
